Implemented support to search Job on Pipeline page(#2adk6nd)
hotwax/job-manager pull request #139
Opened 2022-05-13 12:37 UTC by rathoreprashant

Added search functionality to search jobs by job description 
**Please Review**
Before
![Before](https://user-images.githubusercontent.com/33576503/168284342-ede8f322-8fa1-4e66-924b-cf7e4556a7c3.png)
After
![after](https://user-images.githubusercontent.com/33576503/168284411-858de200-1e4d-408d-aab4-debd9641e801.png)

2022-05-13 12:46 UTC, adityasharma7 requested changes

2022-05-13 12:46 UTC, adityasharma7 commented on src/views/Pipeline.vue
> +      if(this.queryString.length>0) this.findJobs();
I think this do an extra API call for get initial records for all the segments

2022-05-16 06:57 UTC, adityasharma7 requested changes

2022-05-16 06:57 UTC, adityasharma7 commented on src/views/Pipeline.vue
> +        this.store.dispatch('job/fetchPendingJobs', {eComStoreId: this.getCurrentEComStore.productStoreId, viewSize:process.env.VUE_APP_VIEW_SIZE, viewIndex:0,queryString:this.queryString}).then(() =
Spacing issue

2022-05-16 07:11 UTC, rathoreprashant commented on src/views/Pipeline.vue
> +        this.store.dispatch('job/fetchPendingJobs', {eComStoreId: this.getCurrentEComStore.productStoreId, viewSize:process.env.VUE_APP_VIEW_SIZE, viewIndex:0,queryString:this.queryString}).then(() =
Fixed, Please have a look sir

2022-05-16 07:25 UTC, adityasharma7 requested changes

2022-05-16 07:25 UTC, adityasharma7 commented on src/views/Pipeline.vue
> +      <ion-input :placeholder="$t('Search jobs')" v-model="queryString" v-on:keyup.enter="segmentSelected === 'pending' ? getPendingJobs() :segmentSelected === 'running' ? getRunningJobs():getJobHist
```suggestion
      <ion-input :placeholder="$t('Search jobs')" v-model="queryString" v-on:keyup.enter="segmentSelected === 'pending' ? getPendingJobs() : ( segmentSelected === 'running' ? getRunningJobs() : getJobHistory())"/>
```

2022-05-16 07:25 UTC, adityasharma7 commented on src/views/Pipeline.vue
> +          </ion-refresher>
```suggestion
          </ion-refresher>
```

2022-05-16 07:25 UTC, adityasharma7 commented on src/views/Pipeline.vue
> +        this.store.dispatch('job/fetchPendingJobs', {eComStoreId: this.getCurrentEComStore.productStoreId, viewSize:process.env.VUE_APP_VIEW_SIZE, viewIndex:0, queryString:this.queryString}).then(()
```suggestion
        this.store.dispatch('job/fetchPendingJobs', {eComStoreId: this.getCurrentEComStore.productStoreId, viewSize:process.env.VUE_APP_VIEW_SIZE, viewIndex:0, queryString: this.queryString}).then(() => {
```

2022-05-16 07:25 UTC, adityasharma7 commented on src/views/Pipeline.vue
> +      this.queryString="";
```suggestion
      this.queryString = "";
```

2022-05-16 07:26 UTC, adityasharma7 commented on src/store/modules/job/actions.ts
> +
```suggestion

```

2022-05-16 07:29 UTC, adityasharma7 commented on src/views/Pipeline.vue
> +      <ion-input :placeholder="$t('Search jobs')" v-model="queryString" v-on:keyup.enter="segmentSelected === 'pending' ? getPendingJobs() :segmentSelected === 'running' ? getRunningJobs():getJobHist
Add Search jobs to en.json

2022-05-16 12:46 UTC, adityasharma7 commented on src/views/Pipeline.vue
> +        this.store.dispatch('job/fetchPendingJobs', {eComStoreId: this.getCurrentEComStore.productStoreId, viewSize:process.env.VUE_APP_VIEW_SIZE, viewIndex:0, queryString: this.queryString}).then(()
```suggestion
        this.store.dispatch('job/fetchRunningJobs', {eComStoreId: this.getCurrentEComStore.productStoreId, viewSize:process.env.VUE_APP_VIEW_SIZE, viewIndex:0, queryString: this.queryString}).then(() => {
```

2022-05-16 12:47 UTC, adityasharma7 commented on src/views/Pipeline.vue
> +        this.store.dispatch('job/fetchPendingJobs', {eComStoreId: this.getCurrentEComStore.productStoreId, viewSize:process.env.VUE_APP_VIEW_SIZE, viewIndex:0, queryString: this.queryString}).then(()
```suggestion
        this.store.dispatch('job/fetchJobHistory', {eComStoreId: this.getCurrentEComStore.productStoreId, viewSize:process.env.VUE_APP_VIEW_SIZE, viewIndex:0, queryString: this.queryString}).then(() => {
```

2022-05-16 13:15 UTC, adityasharma7 approved these changes

2022-05-16 13:16 UTC, merged