Added types for storing job information(#24b1ket)
hotwax/job-manager pull request #143
Opened 2022-05-16 10:45 UTC by disha1202

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2022-06-01 05:16 UTC, adityasharma7 requested changes

2022-06-01 05:16 UTC, adityasharma7 commented on src/types/Job.ts
> +export interface Job {
Create separate types for each of them:

```suggestion
export interface Enumeration {
  id: String;
  name: String;
  description: String;
  typeId: String;
}
export interface TemporalExpression {
  id: String;
  description: String;
}
export interface Status {
  id: String;
  description: String;
}
export interface Job {
  id: String;
  name: String;
  systemJobEnum: Enumeration;
  parentJobId: String;
  runTime: String;
  serviceName: String;
  status: Status;
  tempExpr: TemporalExpression;
  currentRetryCount: number;
}
```

2022-06-01 05:16 UTC, adityasharma7 commented on src/types/Job.ts
> +export interface Job {
@shashwatbangar

2023-02-01 10:57 UTC, dt2patel commented
closing this MR, not needed anymore

2023-02-01 10:57 UTC, closed without merging