Implemented: Add enum description to job config component(#364trwn)
hotwax/job-manager pull request #207
Opened 2022-08-01 10:21 UTC by shashwatbangar

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2022-08-01 11:26 UTC, dt2patel approved these changes

2022-08-01 11:31 UTC, ymaheshwari1 requested changes

2022-08-01 11:31 UTC, ymaheshwari1 commented on src/components/JobConfiguration.vue
> +            <p>{{ getEnumDescription(currentJob.systemJobEnumId) }}</p>
We won't use getter to fetch the enum description, we are getting description directly on job.

2022-08-02 11:58 UTC, adityasharma7 approved these changes

2022-08-02 11:58 UTC, merged