Added shopify config info at menu footer(#2q9mut9)
hotwax/job-manager pull request #220
Opened 2022-08-17 11:30 UTC by disha1202

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2022-08-17 21:26 UTC, dt2patel requested changes
Some UI changes

2022-08-17 21:26 UTC, dt2patel commented on src/components/Menu.vue
> +            <ion-note slot="end">{{ currentShopifyConfigId }}</ion-note>
we should put this as a p tag below the ion label instead of putting it in the ion note

2022-08-17 21:26 UTC, dt2patel commented on src/views/Settings.vue
> +        <ion-icon :icon="pinOutline" slot="start" />
use basket outline icon.

2022-08-18 06:04 UTC, disha1202 commented on src/views/Settings.vue
> +        <ion-icon :icon="pinOutline" slot="start" />
Used basket outline icon

2022-09-01 11:43 UTC, adityasharma7 approved these changes

2022-09-01 11:45 UTC, merged