Jobs should be fetched and scheduled based upon the selected Shop(#2r65b1c)
hotwax/job-manager pull request #228
Opened 2022-08-23 12:51 UTC by disha1202

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2022-08-29 12:24 UTC, adityasharma7 requested changes

2022-08-29 12:24 UTC, adityasharma7 commented on src/store/modules/user/actions.ts
> +        if (resp.status === 200 && !hasError(resp) && resp.data?.docs.length > 0) {
I think we should null for docs as well

2022-08-29 12:24 UTC, adityasharma7 commented on src/store/modules/user/index.ts
> +      shopifyConfigs: {},
I think this should be array only

2022-08-29 12:24 UTC, adityasharma7 commented on src/store/modules/user/mutation-types.ts
> +export const USER_SHOPIFY_CONFIGS_UPDATED = SN_USER + '/SHOPIFY_CONFIG_LIST_UPDATED'
```suggestion
export const USER_SHOPIFY_CONFIGS_UPDATED = SN_USER + '/SHOPIFY_CONFIGS_UPDATED'
```

2022-08-30 06:03 UTC, ymaheshwari1 requested changes

2022-08-30 06:03 UTC, ymaheshwari1 commented on src/store/modules/job/actions.ts
> +      payload['shopifyConfigId'] = this.state.user.currentShopifyConfig?.shopifyConfigId
Store `this.state.user.currentShopifyConfig` in a variable and check for it's value in `if` condition itself and remove optional chaining.

2022-09-01 06:27 UTC, adityasharma7 requested changes

2022-09-01 06:27 UTC, adityasharma7 commented on src/store/modules/job/actions.ts
> +        'shopId': job.status === "SERVICE_PENDING" ? job.shopId : this.state.user.currentShopifyConfig.shopId,
```suggestion
        'shopId': job.runtimeData?.shopifyConfigId && job.status === "SERVICE_PENDING" ? job.shopId : this.state.user.currentShopifyConfig.shopId,
```

2022-09-01 06:27 UTC, adityasharma7 commented on src/store/modules/job/actions.ts
> +      'shopifyConfigId': job.status === "SERVICE_PENDING" ? job.runtimeData?.shopifyConfigId : this.state.user.currentShopifyConfig.shopifyConfigId,
```suggestion
      'shopifyConfigId': job.runtimeData?.shopifyConfigId && job.status === "SERVICE_PENDING" ? job.runtimeData?.shopifyConfigId : this.state.user.currentShopifyConfig.shopifyConfigId,
```

2022-09-01 06:33 UTC, disha1202 commented on src/store/modules/job/actions.ts
> +        'shopId': job.status === "SERVICE_PENDING" ? job.shopId : this.state.user.currentShopifyConfig.shopId,
Updated the condition.

2022-09-01 06:33 UTC, disha1202 commented on src/store/modules/job/actions.ts
> +      'shopifyConfigId': job.status === "SERVICE_PENDING" ? job.runtimeData?.shopifyConfigId : this.state.user.currentShopifyConfig.shopifyConfigId,
Updated the condition.

2022-09-01 07:11 UTC, adityasharma7 approved these changes

2022-09-01 11:36 UTC, adityasharma7 approved these changes

2022-09-01 11:36 UTC, merged