Implemented: Miscellaneous jobs page(#364ttxy)
hotwax/job-manager pull request #235
Opened 2022-09-06 10:10 UTC by shashwatbangar

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2022-09-08 13:28 UTC, adityasharma7 requested changes

2022-09-08 13:28 UTC, adityasharma7 commented on src/views/Miscellaneous.vue
> +            <p class="ion-text-center">{{ $t("There are no jobs miscellaneous right now")}}</p>
I think we should add it to en.json

2022-09-09 04:25 UTC, shashwatbangar commented on src/views/Miscellaneous.vue
> +            <p class="ion-text-center">{{ $t("There are no jobs miscellaneous right now")}}</p>
Done sir

2022-09-09 05:59 UTC, adityasharma7 approved these changes

2022-09-09 05:59 UTC, merged