Added shop selector to menu footer(#2a7ymj3)
hotwax/job-manager pull request #243
Opened 2022-09-27 07:36 UTC by disha1202

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2022-10-07 12:39 UTC, ymaheshwari1 requested changes

2022-10-07 12:39 UTC, ymaheshwari1 commented on src/components/Menu.vue
> +      emitter.emit("productStoreChanged")
We can move this emit in the if condition.

2022-10-07 12:39 UTC, ymaheshwari1 commented on src/views/Pipeline.vue
> +              <ion-button fill="outline" @click="refreshJobs(undefined, true)">
Instead of passing undefined we can pass event from here.

2022-11-17 10:23 UTC, k2maan commented
- Removed `if(event) event.target.complete();` from refreshJobs functions on Pipeline and Misc pages.
- Since we are using buttons (and not the ion-refresher component) to call the refreshJobs function, `event.target.complete();` isn't required.

2022-12-06 11:17 UTC, merged