Created job-detail component and managed styling of all pages in global css file(#23m9z3e)
hotwax/job-manager pull request #28
Opened 2022-03-16 12:55 UTC by azkyakhan

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2022-03-16 12:59 UTC, azkyakhan commented
![job-detail](https://user-images.githubusercontent.com/82817616/158595230-3429448d-b4ca-4fa8-abe4-651f6dc2d3e3.png)

2022-03-16 12:59 UTC, azkyakhan commented
![localhost_8102_orders](https://user-images.githubusercontent.com/82817616/158595323-a968d50d-d60e-4c91-b63c-133168d3dc4f.png)

2022-03-16 13:18 UTC, azkyakhan commented
https://user-images.githubusercontent.com/82817616/158598624-a940f4b7-d6b8-46f6-9ccb-451bbfbdfa74.mp4

2022-03-17 05:57 UTC, dt2patel requested changes

2022-03-17 05:57 UTC, dt2patel commented on src/components/JobDetail.vue
> +  width: 547px;
lets also add a min width here of 355px
```suggestion
  min-width: 355px;
```

2022-03-17 05:57 UTC, dt2patel commented on src/components/JobDetail.vue
> +  width: 547px;
We can change default width to flex 1 so it grows with size of container now.

2022-03-17 07:13 UTC, closed without merging