Fixed: Removed PO reallocation job from UI(#32129kj)
hotwax/job-manager pull request #301
Opened 2022-11-30 05:44 UTC by shashwatbangar

### Related Issues

Closes #282 

### Short Description and Why It's Useful

Removed reallocation section from preorder page as it do not solve any problem and can create confusion to the user

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2022-11-30 07:30 UTC, k2maan approved these changes

2022-11-30 11:26 UTC, dt2patel commented
We should also remove data for this job from the env files etc.

2022-12-01 05:36 UTC, shashwatbangar commented
> We should also remove data for this job from the env files etc.

Done sir

2022-12-01 06:36 UTC, dt2patel approved these changes
Looks good to me @adityasharma7

2022-12-01 06:44 UTC, adityasharma7 requested changes

2022-12-01 06:44 UTC, adityasharma7 commented on .env.example
>  VUE_APP_JOB_FREQUENCY_TYPE={"BOPIS_CORRECTION":"default","PRE_ORDER_CTLG":"default","ADD_PRODR_TG_SHPFY":"default","REMV_PRODR_TG_SHPFY":"default","ADD_PRODR_SHPG_DTE_SHPFY":"default","REMV_PRODR_SHP
We missed removing it from here

2022-12-01 06:49 UTC, adityasharma7 approved these changes

2022-12-01 06:50 UTC, merged