Fixed: JobConfiguration component displaying runtime of draft jobs(#85zrjdd3b)
hotwax/job-manager pull request #353
Opened 2023-01-18 06:31 UTC by shashwatbangar

### Related Issues

Closes #339 

### Short Description and Why It's Useful

Draft jobs are jobs which are not schedule currently. So if a job is in draft state, it should not have any runtime.

### Screenshots of Visual Changes before/after (If There Are Any)

https://user-images.githubusercontent.com/62360781/213100564-6a4a46bd-bc87-4afb-ba83-226927e83b55.mov

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2023-01-18 11:42 UTC, disha1202 approved these changes

2023-01-19 09:31 UTC, adityasharma7 requested changes

2023-01-19 09:31 UTC, adityasharma7 commented on src/store/modules/job/actions.ts
> +        runTime: ""
We should take care of all the jobs, check code for batch jobs as well

2023-02-02 13:09 UTC, adityasharma7 commented
closing as done in https://github.com/hotwax/job-manager/pull/362

2023-02-02 13:09 UTC, closed without merging