Implemented: predefined and custom option for selecting job run time (#85zrxc0xf)
hotwax/job-manager pull request #449
Opened 2023-04-20 09:55 UTC by k2maan

### Related Issues

Closes #430 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

[Screencast from 20-04-23 12:07:47 PM IST.webm](https://user-images.githubusercontent.com/59442907/233331038-9e245023-a74a-43ba-a147-d3178f62ffda.webm)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2023-04-20 09:59 UTC, k2maan commented
If you add a custom date time but then change to a predefined time, the custom time is not removed from the select options list.

2023-04-24 13:12 UTC, ymaheshwari1 requested changes

2023-04-24 13:12 UTC, ymaheshwari1 commented on src/components/JobConfiguration.vue
> +        <ion-select interface="popover" placeholder="Select" :value="runTime.value" @ionChange="updateRunTime($event)">
Internationalize text.

2023-04-24 13:12 UTC, ymaheshwari1 commented on src/components/JobConfiguration.vue
> +          <ion-select-option v-for="runTime in runTimeOptions" :key="runTime.value" :value="runTime.value">{{ $t(runTime.label) }}</ion-select-option>
Add the hardcoded options in en.json

2023-04-24 13:12 UTC, ymaheshwari1 commented on src/components/JobConfiguration.vue
> +        if (this.runTime.type == 'CUSTOM'
```suggestion
        if (this.runTime.type === 'CUSTOM'
```

2023-04-25 10:19 UTC, ymaheshwari1 approved these changes

2023-04-27 11:23 UTC, adityasharma7 requested changes

2023-05-02 06:42 UTC, adityasharma7 requested changes

2023-05-02 06:44 UTC, adityasharma7 commented on src/components/JobConfiguration.vue
> +      } else {
I think custom option will remain selected in this case

2023-05-08 09:15 UTC, merged