Improved: Added CSS to highlight the selected job card(#742)
hotwax/job-manager pull request #746
Opened 2024-11-25 07:04 UTC by R-Sourabh

### Related Issues

#742 

### Short Description and Why It's Useful

- Implemented a single elevated card state to highlight one job card at a time by conditionally applying CSS.

### Screenshots of Visual Changes before/after (If There Are Any)

![image](https://github.com/user-attachments/assets/0b2305d6-f036-444f-abce-a46ec20487ea)

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2024-11-25 11:00 UTC, ymaheshwari1 requested changes

2024-11-25 11:00 UTC, ymaheshwari1 commented on src/views/Pipeline.vue
> +          <ion-card v-for="job in jobHistory" :key="job.jobId" @click="viewJobConfiguration(job)" :button="isDesktop" :class="{ 'job-card-elevated': elevateJobCard === job.jobId }">
```suggestion
          <ion-card v-for="job in jobHistory" :key="job.jobId" @click="viewJobConfiguration(job)" :button="isDesktop" :class="{ 'selected-job': selectedJobId === job.jobId }">
```

2024-11-25 13:14 UTC, dt2patel commented on src/views/Pipeline.vue
> +  scale: 1.03
```suggestion
  scale: 1.03;
  margin-block: var(--spacer-sm);
```

2024-11-25 13:17 UTC, dt2patel commented on src/views/Pipeline.vue
> +
```suggestion
ion-card {
  transition: .5s all ease;
}
```

Need to fix formatting

2024-11-26 05:25 UTC, dt2patel approved these changes

2024-11-26 06:08 UTC, ymaheshwari1 approved these changes

2024-11-26 06:08 UTC, merged